"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import ez_setup
ez_setup.use_setuptools()

from setuptools import setup

APP = ['MainWindow.pyw']
DATA_FILES = ['MainWindow.pyw', 'Runnables.py', 'sdi_rc2.py', 'sdi_rc3.py', 'Views.py', 'qt.conf', 'sip.so', 'sinastorage']
# OPTIONS = {'argv_emulation': True,
#            'includes': ['sip', 'PyQt4']}
OPTIONS = {'argv_emulation': False,
           'optimize': 2,
           'includes':['sip', 'PyQt4.QtGui', 'PyQt4.QtCore', 'PyQt4._qt'],
           'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtNetwork', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest', 'PyQt4.QtWebKit', 'PyQt4.QtXml', 'PyQt4.phonon'],
           }


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
